### ISSUE TITLE
Use stylelint as a test

### ISSUE THREAD

**Issue by EvgenyOrekhov** [twinscom/stylelint-config#10]
test.css

```css
.test {
    display: block;
}

```

package.json

```diff
"scripts": {
-    "test": "node test.js"
+    "test": "stylelint --config index.json **/*.css"
},
```

This will be catching invalid rule configurations.
